### ISSUE TITLE
Grids don't show after notification system error

### ISSUE THREAD

**Issue by tonin** [perfsonar/maddash#85]
It seems that when maddash encounters an error in the notification system, namely when failing to send an email, the grids then stop loading, i.e. the ```runCheck``` routine is not executed anymore.

Restarting maddash-server, will show the grids again, until the next notification system error. Removing the notification configuration or replacing it with one that works makes the grids work flawlessly.

I guess we would want the grids to continue being displayed, even if the notification system is down.  Maybe even better would be to show an alert on the dashboard saying that the notification system is in error.

Here are some excerpts from MaDDash logs.  In **maddash-server.out** we see the mail system error (timeout here, but the same behavior also happens when the mail relaying is not authorised):
```
Apr 27, 2019 3:32:36 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [localhost:8881]
Apr 27, 2019 3:32:36 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
org.apache.commons.mail.EmailException: Sending the email to the following server failed : pmp-monitoring.geant.org:25
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
        at org.apache.commons.mail.Email.send(Email.java:1448)
        at net.es.maddash.notifications.EmailNotification.send(EmailNotification.java:203)
        at net.es.maddash.jobs.NotifyJob.execute(NotifyJob.java:173)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: pmp-monitoring.geant.org, 25; timeout 60000;
  nested exception is:
        java.net.ConnectException: Connection timed out (Connection timed out)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2053)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697)
        at javax.mail.Service.connect(Service.java:364)
        at javax.mail.Service.connect(Service.java:245)
        at javax.mail.Service.connect(Service.java:194)
        at javax.mail.Transport.send0(Transport.java:253)
        at javax.mail.Transport.send(Transport.java:124)
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
        ... 5 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:580)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:310)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:236)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2019)
        ... 12 more
```

In **maddash-server.netlogger.log** we see that the ```runCheck``` are not happening anymore:
```
level=INFO ts=2019-04-28T00:39:37.111447Z event=maddash.RunCheckJob.execute.runCheck.end guid=eccbeb10-447e-4492-9ecf-672bf15ce5a6 resultMsg=" Average number of paths is 1.000 " col
=psmp-gn-owd-01.gen.ch.geant.net status=0 resultCode=0 grid="PMP - IPv4 traceroute (OWD) - Path Count" row=perfsonar-sonda.rediris.es 
level=INFO ts=2019-04-28T00:39:37.133631Z event=maddash.RunCheckJob.execute.runCheck.end guid=9ef6a631-ae84-4f91-af30-7f2214b7c035 resultMsg=" Average number of paths is 1.000 " col
=psmp-gn-owd-01-mad-es-v4.geant.net status=0 resultCode=0 grid="PMP - IPv4 traceroute (OWD) - Path Count" row=snps-mren.ac.me 
level=INFO ts=2019-04-28T00:39:37.140900Z event=maddash.RunCheckJob.execute.runCheck.end guid=c85b3809-8895-4901-af4f-4a2ecd393c55 resultMsg=" Average number of paths is 1.000 " col
=psmp-gn-owd-01.lon.uk.geant.net status=0 resultCode=0 grid="PMP - IPv4 traceroute (OWD) - Path Count" row=perfsonar.r2.brudie.belnet.net 
level=INFO ts=2019-04-28T00:39:47.980097Z event=maddash.CheckSchedulerJob.execute.start guid=3aa8322e-2dec-443d-93db-5f00aabd059c 
level=INFO ts=2019-04-28T00:39:48.051185Z event=maddash.CheckSchedulerJob.execute.end guid=3aa8322e-2dec-443d-93db-5f00aabd059c status=0 
level=INFO ts=2019-04-28T00:40:08.051379Z event=maddash.CheckSchedulerJob.execute.start guid=3aa8322e-2dec-443d-93db-5f00aabd059c 
level=INFO ts=2019-04-28T00:40:08.101290Z event=maddash.CheckSchedulerJob.execute.end guid=3aa8322e-2dec-443d-93db-5f00aabd059c status=0 
level=INFO ts=2019-04-28T00:40:28.101441Z event=maddash.CheckSchedulerJob.execute.start guid=3aa8322e-2dec-443d-93db-5f00aabd059c 
level=INFO ts=2019-04-28T00:40:28.152355Z event=maddash.CheckSchedulerJob.execute.end guid=3aa8322e-2dec-443d-93db-5f00aabd059c status=0 
```
(...)
```
level=INFO ts=2019-04-28T00:59:30.960653Z event=maddash.CheckSchedulerJob.execute.start guid=3aa8322e-2dec-443d-93db-5f00aabd059c 
level=INFO ts=2019-04-28T00:59:31.011513Z event=maddash.CheckSchedulerJob.execute.end guid=3aa8322e-2dec-443d-93db-5f00aabd059c status=0 
level=INFO ts=2019-04-28T00:59:51.011693Z event=maddash.CheckSchedulerJob.execute.start guid=3aa8322e-2dec-443d-93db-5f00aabd059c 
level=INFO ts=2019-04-28T00:59:51.060878Z event=maddash.CheckSchedulerJob.execute.end guid=3aa8322e-2dec-443d-93db-5f00aabd059c status=0 
level=INFO ts=2019-04-28T01:00:00.001196Z event=maddash.NotifyJob.execute.start guid=b47c9ceb-2479-4029-a529-2902c0716890 
level=INFO ts=2019-04-28T01:00:00.001714Z event=maddash.NativeMesh.init.start guid=b47c9ceb-2479-4029-a529-2902c0716890 
level=INFO ts=2019-04-28T01:00:11.061043Z event=maddash.CheckSchedulerJob.execute.start guid=3aa8322e-2dec-443d-93db-5f00aabd059c 
level=INFO ts=2019-04-28T02:00:00.001151Z event=maddash.NotifyJob.execute.start guid=84293c06-b648-4dd9-b147-7174d5345f75 
level=INFO ts=2019-04-28T03:00:00.000664Z event=maddash.NotifyJob.execute.start guid=2e24b067-5b44-4847-af9e-55a0543be5d8 
level=INFO ts=2019-04-28T04:00:00.000165Z event=maddash.NotifyJob.execute.start guid=e7846df1-9c00-4984-9f77-7bb8cb910c16 
level=INFO ts=2019-04-28T05:00:00.000303Z event=maddash.NotifyJob.execute.start guid=bc279d1a-fcd5-4131-9958-e9d3232510bb 
level=INFO ts=2019-04-28T06:00:00.000747Z event=maddash.NotifyJob.execute.start guid=50bbd641-37a3-4af0-b09c-71eedc8edb9a 
level=INFO ts=2019-04-28T07:00:00.001134Z event=maddash.NotifyJob.execute.start guid=131949fa-a963-416c-b5dd-19a9ebd12d89 
level=INFO ts=2019-04-28T08:00:00.000783Z event=maddash.NotifyJob.execute.start guid=37df8ee2-1a64-45f3-aa82-e211df22b45f 
level=INFO ts=2019-04-28T09:00:00.000218Z event=maddash.NotifyJob.execute.start guid=a19ee185-e6fa-469f-84bb-2ba0d6d6b6d0 
level=INFO ts=2019-04-28T10:00:00.000827Z event=maddash.NotifyJob.execute.start guid=6b670fa5-4f7f-45b2-80d5-5f30e74f6234 
level=INFO ts=2019-04-28T11:00:00.000775Z event=maddash.NotifyJob.execute.start guid=bfaebfdc-042d-4c7f-afa8-aaa9b5df6f21 
level=INFO ts=2019-04-28T12:00:00.001497Z event=maddash.CleanDBJob.execute.start guid=aee5c4f8-b893-42fa-ac05-fc522f17a6fb 
level=INFO ts=2019-04-28T12:00:00.002096Z event=maddash.NotifyJob.execute.start guid=9ed87b10-6209-45dc-90ba-6895acad37b9 
level=INFO ts=2019-04-28T12:58:22.623544Z event=maddash.ResourceManager.getDashboards.start guid=84914166-7ea0-4ec2-a22a-bb89dee2b2d6 
level=INFO ts=2019-04-28T12:58:22.623544Z event=maddash.ResourceManager.getDashboards.start guid=f3f3e69a-c8fb-46da-bc15-e3f65e54bb7a 
level=INFO ts=2019-04-28T12:58:22.623773Z event=maddash.ResourceManager.getDashboards.end guid=84914166-7ea0-4ec2-a22a-bb89dee2b2d6 status=0 
level=INFO ts=2019-04-28T12:58:22.623780Z event=maddash.ResourceManager.getDashboards.end guid=f3f3e69a-c8fb-46da-bc15-e3f65e54bb7a status=0 
level=INFO ts=2019-04-28T12:58:22.838363Z event=maddash.ResourceManager.getGrids.start guid=a6eb2eeb-c0e7-472a-a58a-9a0b2e4c40da 
level=INFO ts=2019-04-28T12:58:22.880351Z event=maddash.ResourceManager.getGrid.start guid=4472813e-8c2e-4edc-a7cc-95b770fa816e 
level=INFO ts=2019-04-28T12:58:22.880600Z event=maddash.NativeMesh.init.start guid=4472813e-8c2e-4edc-a7cc-95b770fa816e 
level=INFO ts=2019-04-28T12:58:22.905031Z event=maddash.ResourceManager.getGrid.start guid=2f0b5e5c-bd6d-40fa-ab7b-d58ba7ebf420 
level=INFO ts=2019-04-28T12:58:22.905094Z event=maddash.NativeMesh.init.start guid=2f0b5e5c-bd6d-40fa-ab7b-d58ba7ebf420 
level=INFO ts=2019-04-28T12:58:22.996064Z event=maddash.ResourceManager.getGrid.start guid=f9005d24-d387-4169-b266-d24a43c712b2 
level=INFO ts=2019-04-28T12:58:22.996089Z event=maddash.ResourceManager.getGrid.start guid=8c047993-58f8-42ef-a6ef-006b33d4e3a3 
level=INFO ts=2019-04-28T12:58:22.996168Z event=maddash.NativeMesh.init.start guid=f9005d24-d387-4169-b266-d24a43c712b2 
level=INFO ts=2019-04-28T12:58:22.996149Z event=maddash.ResourceManager.getGrid.start guid=77fba210-c919-4269-86e7-09bb20ad616b 
level=INFO ts=2019-04-28T12:58:22.996204Z event=maddash.NativeMesh.init.start guid=8c047993-58f8-42ef-a6ef-006b33d4e3a3 
level=INFO ts=2019-04-28T12:58:22.996467Z event=maddash.NativeMesh.init.start guid=77fba210-c919-4269-86e7-09bb20ad616b 
level=INFO ts=2019-04-28T12:59:22.988258Z event=maddash.ResourceManager.getGrid.start guid=f3f3e69a-c8fb-46da-bc15-e3f65e54bb7a 
level=INFO ts=2019-04-28T12:59:22.988373Z event=maddash.NativeMesh.init.start guid=f3f3e69a-c8fb-46da-bc15-e3f65e54bb7a 
level=INFO ts=2019-04-28T12:59:23.037124Z event=maddash.ResourceManager.getGrid.start guid=84914166-7ea0-4ec2-a22a-bb89dee2b2d6 
level=INFO ts=2019-04-28T12:59:23.037223Z event=maddash.NativeMesh.init.start guid=84914166-7ea0-4ec2-a22a-bb89dee2b2d6 
level=INFO ts=2019-04-28T13:00:00.001098Z event=maddash.NotifyJob.execute.start guid=7e2910d0-061e-4e81-8ad0-5b301aec2748 
```

In **maddash-server.log** there is not much of interest:
```
INFO 2019-04-27 00:00:00,004 oldestAllowedTime=1555718400
INFO 2019-04-28 00:00:00,001 oldestAllowedTime=1555804800
```

**Comment by arlake228** [comment]
Antoine has been doing a bunch of legwork debugging this. He got JMX running and watched thread counts, memory, etc in jconsole. After some joint debugging we concluded the DB connection pool was getting exhausted. After digging through the code it looks like it happened when we load notifications from the YAML...which also happens on update of the file. Antoine was able to confirm this was likely the cause by running the `touch` command against maddash.yaml. This caused the busy DB connection count to increase in jconsole. At about 20 (the pool size) the originally reported behavior was observed.
